[package]
name = "diagnostics"
version = "0.1.0"
authors = ["Cyberduc-k <tttymo@gmail.com>"]
edition = "2018"

[dependencies]
termcolor = "1.1.0"
annotate-snippets = { version = "0.8.0", features=["color"] }
